import { FastClient, type StreamHandle } from "@quiclib/web";
import "./style.css";
type Sample = {
  carId: number;
  sequence: number;
  generatedAtMs: number;
  x: number;
  y: number;
  heading: number;
  speed: number;
  queued: number;
  coalesced: number;
};
type Car = {
  id: number;
  stream: StreamHandle;
  streamId: number;
  sample?: Sample;
  received: number;
  paused: boolean;
  slow: boolean;
  trail: [number, number][];
};
const $ = <T extends HTMLElement>(s: string) => document.querySelector<T>(s)!;
const colors = [
  "#16796e",
  "#4871d4",
  "#d8993d",
  "#a46bc3",
  "#cc6871",
  "#547c93",
];
$("#app").innerHTML =
  `<header><a class="brand" href="/">▰ <b>lane</b><span>FLEET LAB</span></a><div class="header-right"><label class="transport-label">Transport <select id="transport"><option value="webtransport">QUIC</option><option value="websocket">WebSocket (TLS)</option></select></label><span id="status" class="badge">● Offline</span><button id="connect" class="primary">Connect fleet ↗</button></div></header>
<main><div class="heading"><div class="eyebrow">LIVE OPERATIONS / SIMULATED CITY</div><h1>Every car. Its own stream<span>.</span></h1><p>A moving city, compare QUIC streams with a shared WebSocket.</p></div>
<div class="stats"><article><label>ACTIVE STREAMS</label><strong id="streams">0 <small>/ 32</small></strong><span><span id="streamKind">One physical stream per vehicle</span></span></article><article><label>MESSAGES / SECOND</label><strong id="rateStat">0</strong><span>Measured incoming telemetry</span></article><article><label>QUEUED MESSAGES</label><strong id="queueStat">0</strong><span>32-message capacity per stream</span></article><article><label>RENDER PERFORMANCE</label><strong id="fps">0 <small>fps</small></strong><span id="total">0 messages received</span></article></div>
<div id="notice" role="status">Ready to connect. Positions are generated by the Rust server.</div>
<div class="workspace"><aside class="fleet"><div class="panel-title"><h2>Vehicles</h2><span id="count">32</span></div><label class="search"><span>⌕</span><input id="search" placeholder="Find a vehicle" aria-label="Find a vehicle"></label><div id="cars"><div class="empty">Connect to bring the city online.</div></div><div class="fleet-foot"><i></i> Reliable, ordered delivery</div></aside>
<section class="map-panel"><div class="map-title"><div><h2>City overview</h2><span><i></i> Local simulation · no map API needed</span></div><label class="toggle"><input id="trails" type="checkbox" checked> Trails</label></div><div class="canvas-wrap"><canvas id="map" aria-label="Live vehicle map. Select a vehicle using the Vehicles list."></canvas><div class="map-tag">N ↑<br><span>LANE CITY</span></div><div class="map-bottom"><span><span id="mapKind">Each moving car = one QUIC stream</span></span><button id="fit">Fit map ⤢</button></div></div><div class="controls"><label>Fleet size<select id="size"><option>1</option><option>16</option><option selected>32</option><option>64</option></select></label><label class="rate-control">Send rate <b id="rateLabel">40 Hz / car</b><input id="rate" type="range" min="10" max="1000" step="10" value="40"></label><button id="pauseAll" disabled>Ⅱ Pause fleet</button></div></section>
<aside class="detail"><div class="panel-title"><h2>Stream inspector</h2><span id="detailTransport" class="badge">QUIC</span></div><div class="vehicle-icon">▰</div><h3 id="carName">Vehicle 001</h3><p class="sub" id="native">Waiting for a stream</p><div class="detail-metrics"><div><strong id="speed">—</strong><label>KM/H</label></div><div><strong id="seq">—</strong><label>SEQUENCE</label></div></div><div class="queue-title"><b>Delivery queue</b><span id="queueLabel">0 / 32</span></div><div id="slots"></div><p class="sub">Oldest updates are coalesced when full, keeping the latest positions.</p><div class="keyvalue"><span>Coalesced updates</span><b id="dropped">0</b></div><div class="keyvalue"><span>Received messages</span><b id="received">0</b></div><button id="pauseCar" disabled>Ⅱ Pause vehicle</button><button id="slowCar" disabled>↘ Slow this stream</button><p class="hint">Add 180 ms delivery delay to this vehicle. Watch its queue fill while the others continue.</p><div class="payload"><label>LATEST POSITION</label><code id="payload">Awaiting telemetry…</code></div></aside></div><footer><span><span id="footerTransport">WEBTRANSPORT · TLS 1.3 · RUST BACKEND</span></span><button id="export">↓ Export session</button></footer></main>`;
let mode: "webtransport" | "websocket" = "webtransport";
const modeName = () => (mode === "webtransport" ? "QUIC" : "WebSocket (TLS)");
let capture:
  | {
      sampleEvery: number;
      seen: number;
      started: number;
      ages: number[];
      carZeroAges: number[];
      frameIntervals: number[];
      bytes: number;
      counts: number[];
      maxQueues: number[];
      initialCoalesced: number[];
      lastReceived: number[];
      maxGaps: number[];
      invalidAges: number;
    }
  | undefined;
let previousFrame = performance.now();
let client: FastClient | undefined;
let cars: Car[] = [];
let selected = 0;
let rate = 40;
let connected = false;
let busy = false;
let allPaused = false;
let total = 0;
let lastTotal = 0;
let lastAt = performance.now();
let frames = 0;
let zoom = 1;
let request = 1;
const encoder = new TextEncoder(),
  decoder = new TextDecoder();
function notice(s: string) {
  $("#notice").textContent = s;
}
function settings(c: Car) {
  return {
    carId: c.id,
    rate,
    paused: c.paused,
    deliveryDelayMs: c.slow ? 180 : 0,
  };
}
async function control(c: Car, initial = false) {
  const ack = await c.stream.sendAndReceive({
    channelId: 512,
    messageType: initial ? 0x1000 : 0x1001,
    requestId: request++,
    payload: encoder.encode(JSON.stringify(settings(c))),
  });
  const data = JSON.parse(decoder.decode(ack.payload));
  c.streamId = data.streamId;
  if (c.paused && c.sample) c.sample.queued = 0;
}
function controls() {
  for (const id of ["pauseAll", "pauseCar", "slowCar"])
    $<HTMLButtonElement>("#" + id).disabled = !connected || busy;
  $("#connect").textContent = connected ? "Disconnect" : "Connect fleet ↗";
  $<HTMLButtonElement>("#connect").disabled = busy;
  $("#status").textContent = connected ? `● Live · ${modeName()}` : "● Offline";
  $("#status").classList.toggle("live", connected);
  $("#pauseAll").textContent = allPaused ? "▶ Resume fleet" : "Ⅱ Pause fleet";
  $<HTMLSelectElement>("#size").disabled = busy;
  $<HTMLSelectElement>("#transport").disabled = busy;
  $("#streamKind").textContent =
    mode === "webtransport"
      ? "One physical stream per vehicle"
      : "Logical channels · one TCP connection";
  $("#mapKind").textContent =
    mode === "webtransport"
      ? "Each moving car = one QUIC stream"
      : "All cars share one WebSocket";
  $("#detailTransport").textContent = modeName();
  $("#footerTransport").textContent =
    mode === "webtransport"
      ? "WEBTRANSPORT · TLS 1.3 · RUST BACKEND"
      : "WEBSOCKET · TLS · RUST BACKEND";
}
async function disconnect() {
  connected = false;
  const old = client;
  client = undefined;
  await old?.close();
  controls();
}
async function connect() {
  if (busy) return;
  busy = true;
  controls();
  try {
    await disconnect();
    cars = [];
    total = lastTotal = 0;
    allPaused = false;
    selected = 0;
    const config = await fetch("/api/config").then((r) => {
      if (!r.ok) throw Error("Backend unavailable");
      return r.json();
    });
    client = new FastClient({
      url: mode === "webtransport" ? config.url : config.websocketUrl,
      transport: mode,
      serverCertificateHashes: [
        {
          algorithm: "sha-256",
          value: Uint8Array.from(atob(config.pin), (c) => c.charCodeAt(0)),
        },
      ],
    });
    const active = client;
    client.onStateChange((s) => {
      if (active === client && (s === "failed" || s === "closed")) {
        connected = false;
        controls();
        notice("Connection closed. Reconnect to start a fresh session.");
      }
    });
    await client.connect();
    const n = Number($<HTMLSelectElement>("#size").value);
    for (let id = 0; id < n; id++) {
      const stream = await client.openStream("car-" + id);
      const c: Car = {
        id,
        stream,
        streamId: -1,
        received: 0,
        paused: false,
        slow: false,
        trail: [],
      };
      cars.push(c);
      stream.onFrame((f) => {
        if (f.messageType !== 0x1002) return;
        const s = JSON.parse(decoder.decode(f.payload)) as Sample;
        if (
          s.carId !== id ||
          !Number.isFinite(s.x) ||
          !Number.isFinite(s.y) ||
          s.queued > 32
        )
          return;
        if (capture) {
          const now = performance.now();
          const age = Date.now() - s.generatedAtMs;
          if (Number.isFinite(age) && age >= 0) {
            if (
              capture.seen++ % capture.sampleEvery === 0 &&
              capture.ages.length < 200000
            )
              capture.ages.push(age);
            if (id === 0 && capture.carZeroAges.length < 20000)
              capture.carZeroAges.push(age);
          } else capture.invalidAges++;
          capture.bytes += 12 + f.payload.byteLength;
          capture.counts[id]++;
          capture.maxQueues[id] = Math.max(capture.maxQueues[id], s.queued);
          capture.maxGaps[id] = Math.max(
            capture.maxGaps[id],
            now - capture.lastReceived[id],
          );
          capture.lastReceived[id] = now;
        }
        c.sample = s;
        c.received++;
        total++;
        c.trail.push([s.x, s.y]);
        if (c.trail.length > 80) c.trail.shift();
      });
      await control(c, true);
    }
    connected = true;
    list();
    notice(
      `${n} ${mode === "webtransport" ? "native QUIC streams" : "logical channels on one encrypted WebSocket"} connected. Select a car to inspect its queue or slow its delivery.`,
    );
  } catch (e) {
    await disconnect();
    notice(
      "Unable to connect: " +
        String(e) +
        (mode === "webtransport"
          ? ". Use a Chromium browser with WebTransport support."
          : ". The local TLS certificate must be trusted by this browser; see the README comparison setup."),
    );
  } finally {
    busy = false;
    controls();
  }
}
function list() {
  const query = $<HTMLInputElement>("#search").value.toLowerCase();
  $("#cars").innerHTML = cars
    .filter((c) =>
      ("vehicle " + String(c.id + 1).padStart(3, "0")).includes(query),
    )
    .map(
      (c) =>
        `<button class="car ${selected === c.id ? "selected" : ""}" data-car="${c.id}"><span class="car-dot" style="background:${colors[c.id % 6]}">▰</span><span><b>Vehicle ${String(c.id + 1).padStart(3, "0")}</b><small>${c.paused ? "Paused" : c.slow ? "Delayed · 180 ms" : rate + " messages / sec target"}</small></span><i class="${c.slow ? "amber" : ""}"></i></button>`,
    )
    .join("");
  $("#count").textContent = String(cars.length);
}
async function action(fn: () => Promise<void>) {
  if (!connected || busy) return;
  busy = true;
  controls();
  try {
    await fn();
    list();
  } catch (e) {
    notice("Control failed: " + String(e));
    await disconnect();
  } finally {
    busy = false;
    controls();
  }
}
$("#connect").onclick = () => (connected ? void disconnect() : void connect());
$("#search").oninput = list;
$("#transport").onchange = () => {
  mode = $<HTMLSelectElement>("#transport").value as typeof mode;
  if (connected) void connect();
  else controls();
};
$("#cars").onclick = (e) => {
  const b = (e.target as HTMLElement).closest<HTMLElement>("[data-car]");
  if (b) {
    selected = Number(b.dataset.car);
    list();
  }
};
$("#size").onchange = () => {
  if (connected) void connect();
  else
    $("#streams").innerHTML =
      `0 <small>/ ${$<HTMLSelectElement>("#size").value}</small>`;
};
$("#rate").oninput = () => {
  $("#rateLabel").textContent =
    $<HTMLInputElement>("#rate").value + " Hz / car";
};
$("#rate").onchange = () => {
  rate = Number($<HTMLInputElement>("#rate").value);
  void action(async () => {
    await Promise.all(cars.map((c) => control(c)));
    notice(
      `Server send rate set to ${rate} messages per second, per active car.`,
    );
  });
};
$("#pauseAll").onclick = () =>
  void action(async () => {
    allPaused = !allPaused;
    await Promise.all(
      cars.map((c) => {
        c.paused = allPaused;
        return control(c);
      }),
    );
  });
$("#pauseCar").onclick = () =>
  void action(async () => {
    const c = cars[selected];
    c.paused = !c.paused;
    allPaused = cars.every((c) => c.paused);
    await control(c);
  });
$("#slowCar").onclick = () =>
  void action(async () => {
    const c = cars[selected];
    c.slow = !c.slow;
    await control(c);
    notice(
      c.slow
        ? "This stream now delivers one message every 180 ms. Its bounded queue coalesces old updates."
        : "Delivery delay removed. This stream is catching up.",
    );
  });
$("#export").onclick = () => {
  const blob = new Blob(
    [
      JSON.stringify(
        {
          exportedAt: new Date().toISOString(),
          transport: modeName(),
          simulated: true,
          totalReceived: total,
          cars: cars.map(
            ({ id, streamId, received, sample, paused, slow }) => ({
              id,
              streamId,
              received,
              sample,
              paused,
              slow,
            }),
          ),
        },
        null,
        2,
      ),
    ],
    { type: "application/json" },
  );
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "lane-session.json";
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
};
const canvas = $<HTMLCanvasElement>("#map"),
  ctx = canvas.getContext("2d")!;
let transform = { scale: 1, x: 0, y: 0 };
const background = document.createElement("canvas");
background.width = 1600;
background.height = 1040;
const bg = background.getContext("2d")!;
bg.fillStyle = "#e9eee9";
bg.fillRect(0, 0, 1600, 1040);
for (let x = 25; x < 1420; x += 240)
  for (let y = 35; y < 960; y += 180) {
    bg.fillStyle = (x + y) % 7 < 3 ? "#d6e3d1" : "#e0e4df";
    bg.beginPath();
    bg.roundRect(x, y, 106, 96, 10);
    bg.fill();
    bg.fillStyle = "#d6ddd6";
    bg.fillRect(x + 15, y + 15, 38, 26);
    bg.fillRect(x + 63, y + 15, 27, 57);
  }
bg.strokeStyle = "#b8d9df";
bg.lineWidth = 100;
bg.beginPath();
bg.moveTo(1510, 0);
bg.bezierCurveTo(1380, 320, 1590, 570, 1450, 1040);
bg.stroke();
for (let x = 160; x <= 1360; x += 240) {
  road(x, 0, x, 1040);
}
for (let y = 160; y <= 880; y += 180) {
  road(0, y, 1600, y);
}
function road(x: number, y: number, a: number, b: number) {
  bg.setLineDash([]);
  bg.strokeStyle = "#ced5cd";
  bg.lineWidth = 37;
  bg.beginPath();
  bg.moveTo(x, y);
  bg.lineTo(a, b);
  bg.stroke();
  bg.strokeStyle = "#fffefa";
  bg.lineWidth = 32;
  bg.stroke();
  bg.setLineDash([8, 10]);
  bg.strokeStyle = "#dce1da";
  bg.lineWidth = 1;
  bg.stroke();
  bg.setLineDash([]);
}
bg.font = "600 17px system-ui";
bg.fillStyle = "#8b9a89";
for (const [s, x, y] of [
  ["NORTH MARKET", 465, 75],
  ["CIVIC SQUARE", 720, 450],
  ["GARDEN DISTRICT", 215, 625],
  ["RIVERSIDE", 1150, 970],
] as const)
  bg.fillText(s, x, y);
function draw() {
  const now = performance.now();
  if (capture && capture.frameIntervals.length < 10000)
    capture.frameIntervals.push(now - previousFrame);
  previousFrame = now;
  frames++;
  const rect = canvas.getBoundingClientRect();
  const dpr = Math.min(devicePixelRatio, 2);
  if (
    canvas.width !== Math.round(rect.width * dpr) ||
    canvas.height !== Math.round(rect.height * dpr)
  ) {
    canvas.width = Math.round(rect.width * dpr);
    canvas.height = Math.round(rect.height * dpr);
  }
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  ctx.clearRect(0, 0, rect.width, rect.height);
  const scale = Math.min(rect.width / 1600, rect.height / 1040) * zoom;
  const x = (rect.width - 1600 * scale) / 2,
    y = (rect.height - 1040 * scale) / 2;
  transform = { scale, x, y };
  ctx.translate(x, y);
  ctx.scale(scale, scale);
  ctx.drawImage(background, 0, 0);
  for (const c of cars) {
    if (!c.sample) continue;
    const s = c.sample,
      color = colors[c.id % 6];
    if ($<HTMLInputElement>("#trails").checked && c.trail.length) {
      ctx.beginPath();
      c.trail.forEach(([x, y], i) => (i ? ctx.lineTo(x, y) : ctx.moveTo(x, y)));
      ctx.strokeStyle = color + "55";
      ctx.lineWidth = 5;
      ctx.stroke();
    }
    ctx.save();
    ctx.translate(s.x, s.y);
    if (c.id === selected) {
      ctx.beginPath();
      ctx.arc(0, 0, 29, 0, Math.PI * 2);
      ctx.fillStyle = color + "22";
      ctx.fill();
      ctx.strokeStyle = color;
      ctx.lineWidth = 2;
      ctx.stroke();
    }
    ctx.rotate(s.heading);
    ctx.fillStyle = "#ffffff";
    ctx.beginPath();
    ctx.roundRect(-18, -11, 36, 22, 6);
    ctx.fill();
    ctx.fillStyle = color;
    ctx.beginPath();
    ctx.roundRect(-16, -9, 32, 18, 5);
    ctx.fill();
    ctx.fillStyle = "#d9efee";
    ctx.fillRect(3, -6, 6, 12);
    ctx.fillStyle = "#fcdf98";
    ctx.fillRect(13, -7, 3, 4);
    ctx.fillRect(13, 3, 3, 4);
    ctx.restore();
  }
  requestAnimationFrame(draw);
}
requestAnimationFrame(draw);
canvas.onclick = (e) => {
  const r = canvas.getBoundingClientRect();
  const x = (e.clientX - r.left - transform.x) / transform.scale,
    y = (e.clientY - r.top - transform.y) / transform.scale;
  let best = 40;
  for (const c of cars) {
    if (!c.sample) continue;
    const d = Math.hypot(c.sample.x - x, c.sample.y - y);
    if (d < best) {
      best = d;
      selected = c.id;
    }
  }
  list();
};
canvas.onwheel = (e) => {
  e.preventDefault();
  zoom = Math.max(1, Math.min(2.5, zoom - e.deltaY * 0.001));
};
$("#fit").onclick = () => {
  zoom = 1;
};
setInterval(() => {
  const c = cars[selected],
    s = c?.sample;
  $("#carName").textContent =
    "Vehicle " + String(selected + 1).padStart(3, "0");
  $("#native").textContent = c
    ? `${mode === "webtransport" ? "Native QUIC stream" : "WebSocket logical channel"} #${c.streamId}`
    : "Waiting for a stream";
  $("#speed").textContent = s
    ? String(Math.round(c.paused ? 0 : s.speed))
    : "—";
  $("#seq").textContent = s ? String(s.sequence) : "—";
  $("#queueLabel").textContent = `${s?.queued ?? 0} / 32`;
  $("#slots").innerHTML = Array.from(
    { length: 32 },
    (_, i) => `<i class="${i < (s?.queued ?? 0) ? "filled" : ""}"></i>`,
  ).join("");
  $("#dropped").textContent = (s?.coalesced ?? 0).toLocaleString();
  $("#received").textContent = (c?.received ?? 0).toLocaleString();
  $("#payload").textContent = s
    ? `x: ${s.x.toFixed(2)}\ny: ${s.y.toFixed(2)}\nseq: ${s.sequence}\nchannel: 0x0200`
    : "Awaiting telemetry…";
  $("#pauseCar").textContent = c?.paused
    ? "▶ Resume vehicle"
    : "Ⅱ Pause vehicle";
  $("#slowCar").textContent = c?.slow
    ? "↗ Restore stream speed"
    : "↘ Slow this stream";
  $("#slowCar").classList.toggle("delayed", !!c?.slow);
  $("#queueStat").textContent = cars
    .reduce((n, c) => n + (c.sample?.queued ?? 0), 0)
    .toLocaleString();
  $("#streams").innerHTML =
    `${connected ? cars.length : 0} <small>/ ${$<HTMLSelectElement>("#size").value}</small>`;
}, 200);
setInterval(() => {
  const now = performance.now(),
    elapsed = (now - lastAt) / 1000;
  $("#rateStat").textContent = Math.round(
    (total - lastTotal) / elapsed,
  ).toLocaleString();
  $("#fps").innerHTML = `${Math.round(frames / elapsed)} <small>fps</small>`;
  $("#total").textContent = total.toLocaleString() + " messages received";
  lastTotal = total;
  frames = 0;
  lastAt = now;
}, 1000);
// Read-only diagnostics for integration tests and browser inspection.
Object.defineProperty(window, "fleetDiagnostics", {
  get: () => ({
    connected,
    total,
    cars: cars.map(({ id, streamId, received, sample, paused, slow }) => ({
      id,
      streamId,
      received,
      sample,
      paused,
      slow,
    })),
  }),
});

// Explicit benchmark controls: same UI, simulation, serializer, queues and render loop.
Object.defineProperty(window, "fleetBenchmark", {
  value: {
    async configure(
      transport: "webtransport" | "websocket",
      count: number,
      hz: number,
      slow = false,
    ) {
      if (![1, 16, 32, 64].includes(count) || hz < 10 || hz > 1000)
        throw Error("Invalid benchmark configuration");
      if (busy) throw Error("Controls busy");
      mode = transport;
      rate = hz;
      $<HTMLSelectElement>("#transport").value = mode;
      $<HTMLSelectElement>("#size").value = String(count);
      $<HTMLInputElement>("#rate").value = String(hz);
      $("#rateLabel").textContent = hz + " Hz / car";
      const started = performance.now();
      await connect();
      if (!connected)
        throw Error($("#notice").textContent ?? "Connection failed");
      const setupMs = performance.now() - started;
      if (slow) {
        cars[0].slow = true;
        await control(cars[0]);
        list();
      }
      return { setupMs, ids: cars.map((c) => c.streamId) };
    },
    start() {
      const now = performance.now();
      capture = {
        sampleEvery: Math.max(1, Math.ceil((cars.length * rate) / 10000)),
        seen: 0,
        started: now,
        ages: [],
        carZeroAges: [],
        frameIntervals: [],
        bytes: 0,
        counts: cars.map(() => 0),
        maxQueues: cars.map(() => 0),
        initialCoalesced: cars.map((c) => c.sample?.coalesced ?? 0),
        lastReceived: cars.map(() => now),
        maxGaps: cars.map(() => 0),
        invalidAges: 0,
      };
    },
    stop() {
      if (!capture) throw Error("No active measurement");
      const result = {
        ...capture,
        elapsedMs: performance.now() - capture.started,
        coalesced: cars.map(
          (c, i) => (c.sample?.coalesced ?? 0) - capture!.initialCoalesced[i],
        ),
      };
      capture = undefined;
      return result;
    },
    async ping() {
      const c = cars[cars.length - 1];
      const started = performance.now();
      await c.stream.sendAndReceive({
        channelId: 512,
        messageType: 0x1004,
        requestId: request++,
        payload: encoder.encode(JSON.stringify(settings(c))),
      });
      return performance.now() - started;
    },
    disconnect,
  },
});
